# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[25,)" #mandatory (24 is current forge version)


# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/Resynth-Minecraft-Mod/Resynth-Mod/issues" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="resynth" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="4.2.0" #mandatory
 # A display name for the mod
displayName="Resynth" #mandatory
# A URL to query for updates for this mod. See the JSON update specification <here>
updateJSONURL="https://resynth-minecraft-mod.github.io/versions.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://resynth-minecraft-mod.github.io/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="" #optional
# A text field displayed in the mod UI
credits="Ki11er_wolf, Aikini (a.k.a. aikinitt), Daniel Murphy" #optional
# A text field displayed in the mod UI
authors="Ki11er_wolf" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''Growable ores, mob drops and resources for Vanilla and Modded Minecraft'''
